### ISSUE TITLE
Commands with underscores aren't colored consistantly with ones without

### ISSUE THREAD

**Issue by Steve0Greatness** [joelcancela/VSCode-cfg-support#6]
Commands with underscores are common in sourcegames, making up most of the commands in these games. It clashes badly with the highlighting for commands like `bind`.

![tf2/cfg/server_247_mannpower.cfg](https://user-images.githubusercontent.com/75220768/209505313-aca9bbb4-bdb7-4f02-a571-7a78e9c406f4.png)

In the image(above) you can see that the commands `mp_timelimit`, `mp_maxrounds`, `tf_powerup_mode`, `tf_flag_caps_per_round`, and `mp_forceautoteam` is blue whereas `exec` is red. This is clash in the colors they use annoys me, it's extremely hard to ignore.

**Comment by joelcancela** [comment]
Hi @Steve0Greatness,
Thanks for your interest in my extension
Unfortunately the syntax highlighting rendering depends on the skin you use on VSCode
On my end I use: Community Material Theme - Ocean High Contrast theme
and your code looks like this : 
![image](https://user-images.githubusercontent.com/18258410/209564522-fc6c3c52-6e88-4460-ac88-96fb25b4bbdc.png)

If you could just provide me with the skin you are using I could have look and try to find a fix if it's even possible :)
Otherwise I suggest you to find a theme that suits you with better syntax highlighting support

Regards,
Joël

**Comment by Steve0Greatness** [comment]
@joelcancela, I'm using the [GitHub Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme). More specifically, I'm using the variant simply known as `GitHub Dark`. Hope this helps.

**Comment by joelcancela** [comment]
Hi @Steve0Greatness,
Yes it helps it would now look like this with your theme:
![image](https://user-images.githubusercontent.com/18258410/209705698-1d40481a-ee8a-43de-bdb4-092ef7da8bd9.png)
Release incoming in a few minutes
